name: Sync To Internal GitLab

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  workflow_dispatch:

concurrency:
  group: sync-to-internal-gitlab
  cancel-in-progress: false

jobs:
  mirror:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Mirror current repo to internal GitLab
        uses: ./
        with:
          src_platform: github
          src_account: ${{ github.repository_owner }}
          dst_platform: gitlab
          dst_account: ${{ secrets.GITLAB_NAMESPACE }}
          dst_endpoint: ${{ secrets.GITLAB_SSH_URL }}
          dst_api_endpoint: ${{ secrets.GITLAB_URL }}
          dst_key: ${{ secrets.GITLAB_SSH_KEY }}
          dst_transport: ssh
          dst_token: ${{ secrets.GITLAB_TOKEN }}
          repos: |
            static:
              - ${{ github.event.repository.name }}
            
            refs: 
              branches:
                include: ['v*']
              tags:
                include: ['*']
          push_strategy: force
