on:
  push:
  pull_request_target:
    branches: [master]
name: Tests / test-org-mirror
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Mirror Github to Gitee
        uses: ./.
        with:
          src_platform: github
          src_account: hub-mirror-action
          dst_platform: gitee
          dst_account: hub-mirror-action
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          src_account_type: org
          dst_account_type: org
          repos: |
            include:
              - normal
              - test
              - empty
            exclude:
              - test
          push_strategy: force
          log_level: DEBUG
