on:
  push:
  pull_request_target:
    branches: [master]
name: Tests / test-user-mirror-cached
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Cache src repos
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/hub-mirror-cache
          key: ${{ runner.os }}-hub-repos-cache-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-hub-repos-cache

      - name: Mirror Github to Gitee with cache
        uses: ./.
        with:
          src_platform: github
          src_account: Yikun
          dst_platform: gitee
          dst_account: yikunkero
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          cache_path: hub-mirror-cache
          repos: |
            include:
              - hub-mirror-action
              - hexo-migrator-github-issue
          push_strategy: force

      - name: Print cache path
        run: |
          ls -la ${{ github.workspace }}/hub-mirror-cache
